### ISSUE TITLE
Create separate buttons for compilation and execution

### ISSUE THREAD

**Issue by vaibhav276** [babrubhan/Collab_TD#2]
"Compile" = Only compile
"Run" = Compile + Run

**Comment by babrubhan** [comment]
Done.

**Comment by babrubhan** [comment]
There are two buttons in UI "compile" and "run".  
Compile = Only compile (prints a msg "Compilation Ok")
Run = Compile + Run (Output)

**Comment by babrubhan** [comment]
If the user clicks on "Run" button before compiling the code it will give a msg "Code is not compiled || compilation Error"

**Comment by vaibhav276** [comment]
Since Run = Compile + Run, it should not give "Code is not compiled" when user clicks on Run

**Comment by babrubhan** [comment]
Yes, I removed it. There was a misunderstanding about the button's actual functionality and I was thinking of using the same compilation code.
